-- Initialize all databases for local development

CREATE DATABASE IF NOT EXISTS account;
CREATE DATABASE IF NOT EXISTS balance;
CREATE DATABASE IF NOT EXISTS currency;
CREATE DATABASE IF NOT EXISTS holdings;
CREATE DATABASE IF NOT EXISTS projections;
CREATE DATABASE IF NOT EXISTS sync;
CREATE DATABASE IF NOT EXISTS transaction;
